apiVersion: v1
kind: Service
metadata:
  name: gitone
  labels:
    {{- include "gitone.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gitone.selectorLabels" . | nindent 4 }}
  ports:
    - name: public
      protocol: TCP
      port: {{ .Values.service.publicPort }}
      targetPort: public
    {{- if .Values.ssh.enabled }}
    - name: ssh
      protocol: TCP
      port: {{ .Values.ssh.servicePort }}
      targetPort: ssh
    {{- end }}
